name: Release ZigWin32 Bindings - win10+

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup:
    runs-on: WIN-BUILD
    steps:
      - name: Checkout ngixi-builds repo
        uses: actions/checkout@v4
        with:
          clean: false

      - uses: ./.github/actions/setup-build
        with:
          build-dir: zig-win32-build

  build-zig:
    runs-on: WIN-BUILD
    needs: setup
    permissions:
      contents: write
    defaults:
      run:
        working-directory: zig-win32-build

    steps:
      - name: Clone ZigWin32Gen
        shell: pwsh
        run: |
          # Remove existing directory if it exists
          if (Test-Path zigwin32gen) {
            Remove-Item zigwin32gen -Recurse -Force
          }
          git clone ${{ vars.ZIGGEN_REPO }} zigwin32gen

      - name: Checkout ZigWin32Gen tag
        shell: pwsh
        run: |
          cd zigwin32gen
          git fetch --tags --force --quiet
          git checkout --quiet ${{ vars.ZIGGEN_TAG }}
          git rev-parse --short HEAD | Out-File -Encoding ascii ..\ZIG_WIN32_GIT.txt

      - name: Build ZigWin32Gen
        shell: pwsh
        run: |
          cd zigwin32gen
          zig build
          # Verify build output
          if (Test-Path "zig-out") {
            Write-Host "Build successful - zig-out directory exists"
            Get-ChildItem "zig-out" -Name | Select-Object -First 5
          } else {
            Write-Host "ERROR: Build failed - zig-out directory not found"
            exit 1
          }

      - name: Create release branch
        shell: pwsh
        run: |
          # Delete release-branch folder if it exists
          if (Test-Path "release-branch") {
            Remove-Item "release-branch" -Recurse -Force
          }
          
          # Create release-branch folder
          New-Item -ItemType Directory -Path "release-branch" -Force
          
          # Reclone ngixi-builds repo into release-branch
          cd release-branch
          git clone https://github.com/ngixi/ngixi-builds.git .
          
          # Create orphaned branch with no contents
          git checkout --orphan "zig-win32-bindings-${{ vars.ZIGGEN_TAG }}"
          
          # Reset to the first commit of the repo (empty state)
          $firstCommit = git rev-list --max-parents=0 HEAD
          git reset --hard $firstCommit
          
          # Copy zig-out contents from parent folder
          Copy-Item -Recurse "..\zigwin32gen\zig-out\*" . -Force
          
          # Add and commit
          git add .
          git commit -m "Zig Win32 Bindings v${{ vars.ZIGGEN_TAG }}"
          
          # Force push the release branch
          git push origin "zig-win32-bindings-${{ vars.ZIGGEN_TAG }}" --force

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: zig-win32-${{ vars.ZIGGEN_TAG }}
          target_commitish: zig-win32-bindings-${{ vars.ZIGGEN_TAG }}
          name: Zig Win32 Bindings ${{ vars.ZIGGEN_TAG }}
          body: |
            Zig Windows API Bindings v${{ vars.ZIGGEN_TAG }}
            Generated from ${{ vars.ZIGGEN_REPO }}

            Download the source code archive to get the Zig binding files.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
